id: D2FFA0B27
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:55:52+00:00'
last_modified: '2022-05-26T12:42:04.398228+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    40b5:
      image_group_id: I1PD95883
      title: གཙུག་ཏོར་དྲི་མེད་ཀྱི་གཟུངས་ཆོག།
      total_pages: 1044
      order: 38
      base_file: 40b5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
