id: P2BC4EB7C
initial_creation_type: ocr
source_metadata:
  volumes:
    7e0afee9e10649e9b31de25c0930a9a8:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: གཙུག་ཏོར་དྲི་མེད་ཀྱི་གཟུངས་ཆོག།
      total_pages: 1044
      volume_number: 38
